### ISSUE TITLE
Qualifying from some non final rounds counts as win

### ISSUE THREAD

**Issue by johnathan-codes** [ShootMe/FallGuysStats#140]
For example in Hex-A-Ton, where the rounds are Hex-A-Gone, Hex-A-Ring and Hex-A-Terrestrial, if you qualify from any round it is counted as a win.

Ex. qualifying from round one and dying in round 2 will count as 1 win
Qualifying from round one and two but dying in round three counts as 2 wins.
An winning the whole show counts as 3 wins.

**Comment by BlueLight218** [comment]
With the recent addition of the new Finals Marathon show, this issue has popped up again. This issue is not limited to just specific shows, it seems like any final that is not being played as a final in game will cause the issue. The original post displays the issue perfectly, if you play final rounds in a round that isn't technically the final, the tracker will count a qualification as a victory. I have attached an image of my tracker after playing the new Finals Marathon (only final rounds) show, even though I only reached an actual final round four times and won, the tracker thinks that I reached a final 23 times and won 22 games. This obviously has some unintended results, as I currently have a 440% winrate.
![TrackerDisplayingTooManyWins](https://user-images.githubusercontent.com/74394040/204662681-eedbf650-8073-408b-93d6-6b73cb9b21e5.png)
