### ISSUE TITLE
New update broke everything

### ISSUE THREAD

**Issue by Randommer** [ShootMe/FallGuysStats#141]
The game got an update this morning. Live tracking and log recovery doesn't work anymore.

**Comment by adamkelly86** [comment]
[20221018-1.log](https://github.com/ShootMe/FallGuysStats/files/9814663/20221018-1.log)

Example log file - 1 round of Sweet Thieves

**Comment by adamkelly86** [comment]
Hmm, possible cause

10/18/2022: [GameStateMachine] Replacing FGClient.StateMainMenu with FGClient.StateMatchmaking
10/18/2022: [StateMatchmaking] Begin matchmaking solo

Compared to a log from 19th Sept 

19:30:01.317: [GameStateMachine] Replacing FGClient.StateMainMenu with FGClient.StateFNMMSMatchmaking
19:30:01.317: [StateMatchmaking] Begin party communications

**Comment by adamkelly86** [comment]
Hmm, so looking at the event outcome - it seems that stamps have the date rather than time stored. 

Taking this win from Sweet Thieves

10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [17] XXX (ps5) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [27] XXX (ps4) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [16] XXX (win) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [18] XXX (win) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [22] XXX (win) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [21] XXX (win) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [19] XXY (win) (FG.Common.MPGNetObject)
10/18/2022: Cannot cycle spectators when not using the player spectator camera.
MPG.Utility.CustomLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
MPG.Utility.MPGMonoBehaviour:LogWarning(String)
FG.Common.CameraDirector:CyclePlayerSpectatorCamera(Boolean)
FG.Common.CameraDirector:RemoveSpectatorCameraTarget(GameObject)
FGClient.ClientGameManager:_untrackPlayerSpawn(MPGNetObject)
FGClient.ClientGameManager:_handleClientUnspawnNetObject(MPGNetObject)
System.Action`1:Invoke(T)
FG.Common.MPGNetObjectManager:UnspawnNetObject(MPGNetID, UnspawnGameObjectPolicy)
FGClient.ClientGameManager:HandleServerUnspawnNetObject(GameMessageServerUnspawnObject)
System.Action`1:Invoke(T)
FGClient.ClientNetworkMessageProcessor:processMessage(GameConnection, GameMessageBase)
FG.Common.UnityNetworkMessageHandler:HandleAndFreeInboundGameMessage(MessageEnvelope)
FG.Common.UnityNetworkMessageHandler:PeekAndHandleMessage(NetworkMessage, GameConnection)
Spine.Unity.InstructionDelegate:Invoke(SkeletonRendererInstruction)
UnityEngine.Networking.NetworkConnection:HandleReader(NetworkReader, Int32, Int32)
UnityEngine.Networking.NetworkClient:InternalNetworkDataReceive()
UnityEngine.Networking.NetworkClient:NetworkDataReceive()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [20] XXX (win) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [24] XXX (switch) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [23] XXX (win) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [25] Chℝɪsproツ (switch) (FG.Common.MPGNetObject)
10/18/2022: [ClientGameManager] Handling unspawn for player FallGuy [26] Moppel2099 (ps4) (FG.Common.MPGNetObject)
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=5 is succeeded=True
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=9 is succeeded=True
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=4 is succeeded=True
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=8 is succeeded=True
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=12 is succeeded=True
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=10 is succeeded=True
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=11 is succeeded=True
10/18/2022: SquadManager::GetSquadScore squadId0 not found return 0
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=2 is succeeded=True
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=3 is succeeded=False
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=6 is succeeded=False
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=1 is succeeded=False
10/18/2022: ClientGameManager::HandleServerPlayerProgress PlayerId=7 is succeeded=False
10/18/2022: Team 0 score = 0
10/18/2022: Team 1 score = 12
10/18/2022: SquadManager::GetSquadScore squadId0 not found return 0
10/18/2022: [ClientGameManager] Server notifying that the round is over.

I'll see if ShootMe can see anything useful, but I'm guessing that if there's no actual timestamp (like 19:30:01.317) , there is nothing to calculate from.

**Comment by VoidDaemon** [comment]
As adamkelly86 has shown, the log lines have had their timestamp changed to a datestamp which means round times can't be calculated. However, everything else appears to be the same, so it should be possible to still track round progress and wins/losses.

**Comment by alexjlockwood** [comment]
I don't see any information about round names in the log either, unless I'm missing something.

**Comment by VoidDaemon** [comment]
There are two ways the tracker gets the round, from parsing either the round loading line itself e.g.

10/19/2022: [StateGameLoading] Finished loading game level, assumed to be round_gauntlet_02_ss2_launch. Duration: 2.39s

or if it can't work it out from that, then from the splash screen loading line e.g.

10/19/2022: [StateGameLoading] Loading game level scene FallGuy_Gauntlet_02_01 - frame 13343

where gauntlet_02 is the internal name for Dizzy Heights (each round has its own internal name).

**Comment by ShootMe** [comment]
With the removal of the timestamps it will take some effort to change everything to work close to like it used to. I don't really have that much time these days to do that unfortunately. If anyone else can figure something out and send a pull request I would use that, but don't have the time to do it myself at this point.

**Comment by niotacz** [comment]
so @ShootMe auto update system will update and fix this issue automatic or you need give new file?

**Comment by qutrits** [comment]
> 

Can you provide me with the log file before the update?

**Comment by qutrits** [comment]
@adamkelly86 @ShootMe Can you provide me with the log file before the update?

**Comment by Randommer** [comment]
You can look at some of my logs from last june.

[Player-prev.log](https://github.com/ShootMe/FallGuysStats/files/9887203/Player-prev.log)
[Player-prev.log](https://github.com/ShootMe/FallGuysStats/files/9887226/Player-prev.log)
[Player.log](https://github.com/ShootMe/FallGuysStats/files/9887228/Player.log)
[Player.log](https://github.com/ShootMe/FallGuysStats/files/9887236/Player.log)
[Player-prev.log](https://github.com/ShootMe/FallGuysStats/files/9887240/Player-prev.log)

**Comment by qutrits** [comment]
It's not perfect, but I've modified the source code. Just overwrite the existing folder and run. please test.

[FallGuyStatsManualUpdate.zip](https://github.com/ShootMe/FallGuysStats/files/9888157/FallGuyStatsManualUpdate.zip)

**Comment by AymericSpin** [comment]
> It's not perfect, but I've modified the source code. Just overwrite the existing folder and run. please test.
> 
> [FallGuyStatsManualUpdate.zip](https://github.com/ShootMe/FallGuysStats/files/9888157/FallGuyStatsManualUpdate.zip)

It doesn't work, the problem persists. My stats not updating after a round is over

**Comment by niotacz** [comment]
ok

**Comment by qutrits** [comment]
2022-10-29: [GameSession] Changing state from Countdown to Playing

2022-10-29: [ClientGameManager] Handling unspawn for player FallGuy [52] julyan-papa (ps4) (FG.Common.MPGNetObject)

Guys. I've been reviewing the source code all day today, but since the log file does not provide the start and end time information of the round after the update, there seems to be a limit to the way to read the current FallGuysStats log file. Therefore, the lap time function of the round is abandoned, and information such as the timer function, number of people, and ping can be displayed.

**Comment by AymericKing** [comment]
> 2022-10-29: [GameSession] Changing state from Countdown to Playing
> 
> 2022-10-29: [ClientGameManager] Handling unspawn for player FallGuy [52] julyan-papa (ps4) (FG.Common.MPGNetObject)
> 
> Guys. I've been reviewing the source code all day today, but since the log file does not provide the start and end time information of the round after the update, there seems to be a limit to the way to read the current FallGuysStats log file. Therefore, the lap time function of the round is abandoned, and information such as the timer function, number of people, and ping can be displayed.
> 
> I'm not sure why Mediatonic suddenly deleted the time information from the log file, but if they leave the time information in the log file again through a later update, then all functions will be possible.
 
 you update the tracker.exe or not?

**Comment by qutrits** [comment]
What does tracker.exe mean?

**Comment by AymericKing** [comment]
> What does tracker.exe mean?

FallGuyStatsManualUpdate.zip i mean

**Comment by qutrits** [comment]
If you download FallGuyStatsManualUpdate.zip that I posted in the above comment and overwrite it in the existing folder, the timer function, number of people, and ping will be displayed.

**Comment by AymericKing** [comment]
> If you download FallGuyStatsManualUpdate.zip that I posted in the above comment and overwrite it in the existing folder, the timer function, number of people, and ping will be displayed.

The problem with your file is that it doesn't update the stats after a completed round. We've had this bug for 2 weeks and the creator of the software does nothing to fix it.

**Comment by ThreesFG** [comment]
I have taken a stab at this myself, would like some feedback on my fork: https://github.com/ThreesFG/FallGuysStats 

It reconstructs the log file by inserting timing data on the fly (requires the stat tracker to be running before starting the show). Round timings won't be exact but appear to be pretty close (within ~0.1 second). All tracking from 8.0.0 should be functional again, aside from the Ping on the overlay. I made it create a backup copy of the database file when running my version for the first time (juuuuuust in case).

I haven't spent a ton of time on it, so would like some confirmation that I'm not breaking things before submitting a pull request.

**Comment by bermanskid** [comment]
> I have taken a stab at this myself, would like some feedback on my fork: https://github.com/ThreesFG/FallGuysStats
> 
> It reconstructs the log file by inserting timing data on the fly (requires the stat tracker to be running before starting the show). Round timings won't be exact but appear to be pretty close (within ~0.1 second). All tracking from 8.0.0 should be functional again, aside from the Ping on the overlay. I made it create a backup copy of the database file when running my version for the first time (juuuuuust in case).
> 
> I haven't spent a ton of time on it, so would like some confirmation that I'm not breaking things before submitting a pull request.

Giving it a try now and it seems to be working. Received an error message to start but doesn't seem to be affecting the stat tracking so far.

**Comment by ThreesFG** [comment]
@bermanskid do you recall what the error message said? I have it show an alert the first time you run my version (info on timings not being exact and usage instructions), so want to rule out that you just saw that message.

**Comment by bermanskid** [comment]
That alert did pop up. The error message popped up after. I’ll try to get a screenshot of it next time I play.

Other than that the tracker seemed to be working well. Appreciate the work on that!

**Comment by bermanskid** [comment]
So the error message hasn't popped up today. I even restarted my PC to see if it would, but nope. Tracker is still working though!

**Comment by ThreesFG** [comment]
@neokidaze For your Log Path in the Settings screen, make sure this is either blank or is pointing at the logs folder. Your screenshot suggests this value was set to "C:\Program Files (x86)\Steam\steamapps\common\Fall Guys\FallGuys_client_game.exe" , which is incorrect.

![image](https://user-images.githubusercontent.com/117041464/199247673-a1be4589-da08-4e49-8875-25386b1b890d.png)

**Comment by neokidaze** [comment]
@ThreesFG Understood! Thank you.

**Comment by ThreesFG** [comment]
I have submitted a pull request to fix this issue and support the new log format: https://github.com/ShootMe/FallGuysStats/pull/151

**Comment by mrsilverhawk** [comment]
How do you download the fix? anything I click on wont save to pc

**Comment by Micdu70** [comment]
> How do you download the fix? anything I click on wont save to pc

Simply download the latest FallGuysStats' version (1.130). Chek the `README.md` file. ;)
