### ISSUE TITLE
Fall Ball - [BEST] Filter not working

### ISSUE THREAD

**Issue by elanjcoop** [ShootMe/FallGuysStats#22]
Showed 2 but was much higher

**Comment by ShootMe** [comment]
The tracker will only have access to the info since you started using it. It can't determine High Score from anytime before you started using it.

If you mean you have a score higher than 2 when opening the Level Details by clicking on the blue ( i ) icon next to "Fall Ball" then ill need your data.db to see why it's not calculating it correctly. The overlay also will only look at the games specified in the Settings page for the Fastest / Longest setting. So if that is set to 'Day' it will only pull the High Score for that Day, and nothing before.

If you are encountering something else, please expand.

**Comment by elanjcoop** [comment]
Just looked into it; I thought I had more games logged than I did. Sorry to bother!
