### ISSUE TITLE
[Bug]: If the tracker function cannot be used normally, the following error occurs

### ISSUE THREAD

**Issue by cride134** [ShootMe/FallGuysStats#228]
### What happened?

I can still use the tracker normally in the morning, but the following error keeps getting after the fall guys update is completed ，thank you
![`$5LW%6JFEPT{M8PW)EZBZN](https://github.com/ShootMe/FallGuysStats/assets/117172934/541d4d48-92cf-41e9-b1c7-6bd58ecc072e)
[FallGuysStats.zip](https://github.com/ShootMe/FallGuysStats/files/11665400/FallGuysStats.zip)

### Platform

None

**Comment by Micdu70** [comment]
[FIXED_FallGuysStats_16.zip](https://github.com/ShootMe/FallGuysStats/files/11676534/FIXED_FallGuysStats_16.zip)

Note: "data-log.db" should be a temporary file but since that this following line was added in code => https://github.com/ShootMe/FallGuysStats/blob/51ba7b06ea15caa3e27698763d69320b41aeb889/Views/Stats.cs#L1520

"data-log.db" is never emptied/deleted and it may cause issues (I guess...).

**Comment by cride134** [comment]
> 

thank you so much.I've fixed it when I use your data.db.thank you
