### ISSUE TITLE
My own difficulties.

### ISSUE THREAD

**Issue by qutrits** [ShootMe/FallGuysStats#264]
### What is your question?

There is a habit I developed while updating this program. For each update, I create my own test case and test it while playing the game. As a result, it became difficult to enjoy the game properly. I work hard at testing, but there are limits to doing it alone. Issues registered here help with bug fixing, but since the frequency of issues being registered is very low, I mostly fix bugs found while playing the game. @Micdu70 If it weren't for this friend, maintaining this program would have ended a long time ago. Although I couldn't say it, he's a friend I'm really thankful for.

**Comment by FallGuysStatsStan** [comment]
Maybe we can find a group of people to share the routine testing work? That way you don't have to spoil your own enjoyment of the game repeating the same tests. I usually play daily and would be happy to help with this. 

Also it is very impressive how the tracker is updated more than the game itself, but nobody will be hurt/nobody should complain if you take a break and the tracker gets updated less frequently. 

I think the tracker is great and only created a GitHub account in order to star the repository. Unfortunately I don't currently have the technical skill to contribute to the code without breaking something :-D
