### ISSUE TITLE
Overlay Max FPS 60

### ISSUE THREAD

**Issue by ATTAGswag** [ShootMe/FallGuysStats#49]
When I launch the Stat Tracker/Overlay, it seems it won't allow my Fall Guys game to run above 60 FPS.  I close it, and I can run it at 144 FPS without many issues.
I've attempted to mess around with my settings, analyze running program stats, among some other things and I can't figure out a solution.

I'd be grateful for any help.
Let me know if any other information is needed.

-Here are some specs for some background info:
Processor - Intel Core i-7 7700K
Motherboard - ASUS Maximus IX Formula
Graphics Card - GEFORCE GTX 1080
Solid State Drive - Samsung 500GB 850 Evo
Cooling - ETS-T40
Monitor - MG248Q Gaming Monitor - 1 ms Trace Free - 144 HZ Refresh Rate
Mouse - Razer Naga
Mousepad - Razer Vespula
Keyboard - Razer Deathstalker
2nd Screen - A POS used for chat
Headset - Hyper - X
Webcam - HD 1080p Logitech

**Comment by ShootMe** [comment]
I don't really know.

The only thing I can imagine is that since the UI is built on basic WinForm controls, which use very old GDI+ drawing APIs, it could be causing some weird performance mismatch with the game.

I only run 60hz dual screens so I can't test something like your setup unfortunately.

Not sure if your 2nd monitor is also 144hz or is 60hz. That could be part of it. Maybe also could be which monitor you have the stat tracker on. Try putting them both on one monitor or the other and see.

**Comment by ShootMe** [comment]
Closing since no additional info.
